general.import = [
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml",
]

[font]
normal.family = "Hack Nerd Font"
size = 8.0

[env]
# This (hopefully) makes sure font size is the same across monitors
WINIT_X11_SCALE_FACTOR = "1.66"
