"$schema" = 'https://starship.rs/config-schema.json'

format = """
[$os$username](bg:grad2 fg:white)\
[](bg:grad4 fg:grad2)\
[$directory](bg:grad4 fg:white)\
[](fg:grad4 bg:grad6)\
[$git_branch$git_status](bg:grad6 fg:white)\
[](fg:grad6 bg:grad8)\
[$c$rust$golang$nodejs$php$java$kotlin$haskell$python](bg:grad8 fg:white)\
[](fg:grad8 bg:grad10)\
[$docker_context](bg:grad10 fg:white)\
[](fg:grad10 bg:grad12)\
[$time](bg:grad12 fg:white)\
[](fg:grad12)\
$line_break$character"""

palette = 'gruvbox_material_hard_dark'

[palettes.gruvbox_material_hard_dark]
bg_dim='#141617'
bg0='#1d2021'
bg1='#282828'
bg2='#282828'
bg3='#3c3836'
bg4='#3c3836'
bg5='#504945'
bg_statusline1='#282828'
bg_statusline2='#32302f'
bg_statusline3='#504945'
bg_diff_green='#32361a'
bg_visual_green='#333e34'
bg_diff_red='#3c1f1e'
bg_visual_red='#442e2d'
bg_diff_blue='#0d3138'
bg_visual_blue='#2e3b3b'
bg_visual_yellow='#473c29'
bg_current_word='#32302f'
fg0='#d4be98'
fg1='#ddc7a1'
red='#ea6962'
orange='#e78a4e'
yellow='#d8a657'
green='#a9b665'
aqua='#89b482'
blue='#7daea3'
purple='#d3869b'
bg_red='#ea6962'
bg_green='#a9b665'
bg_yellow='#d8a657'
grad1='#7a711f'
grad2='#736722'
grad3='#6d5e25'
grad4='#675727'
grad5='#61502a'
grad6='#5b4a2c'
grad7='#55452e'
grad8='#4f4130'
grad9='#4a3d31'
grad10='#453b33'
grad11='#403834'
grad12='#3b3735'

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"code" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[docker_context]
symbol = ""
format = ' $symbol( $context)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:white)'
error_symbol = '[❯](bold fg:red)'
